exclude: ^(docs|gittrail/testdata)/
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-merge-conflict
    - id: check-toml
    - id: check-yaml
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort
- repo: https://github.com/asottile/pyupgrade
  rev: v2.29.1
  hooks:
    - id: pyupgrade
      args: [--py37-plus]
- repo: https://github.com/psf/black
  rev: 21.11b1
  hooks:
    - id: black
- repo: https://github.com/PyCQA/pylint
  rev: v2.12.1
  hooks:
    - id: pylint
      args: [--rcfile=.pylintrc]
      files: ^gittrail/
      exclude: (.*)test_(.*).py
