name: pipeline

on: [push, pull_request]

jobs:
  test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --statistics
    - name: Test with pytest
      run: |
        pytest --cov=./gittrail --cov-report xml --cov-report term-missing gittrail/
    - name: Upload coverage
      uses: codecov/codecov-action@v2
      if: matrix.python-version == 3.9
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
    - name: Test Wheel install and import
      run: |
        python setup.py bdist_wheel
        cd dist
        pip install gittrail*.whl
        python -c "import gittrail; print(gittrail.__version__)"
